cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED IRO_TOOL_ROOT)
  message(FATAL_ERROR "IRO_TOOL_ROOT is required")
endif()
if(NOT DEFINED IRO_TOOL_BUILD_DIR)
  message(FATAL_ERROR "IRO_TOOL_BUILD_DIR is required")
endif()

set(GEN_PROBE_BIN "${IRO_TOOL_BUILD_DIR}/gen_probe")
set(LAYOUT_PARSE_BIN "${IRO_TOOL_BUILD_DIR}/layout_parse")

foreach(bin IN LISTS GEN_PROBE_BIN LAYOUT_PARSE_BIN)
  if(NOT EXISTS "${bin}")
    message(FATAL_ERROR "Missing required binary: ${bin}")
  endif()
endforeach()

find_program(CC_EXECUTABLE NAMES cc clang gcc)
if(NOT CC_EXECUTABLE)
  message(FATAL_ERROR "No C compiler found (cc/clang/gcc)")
endif()

set(WORK_DIR "${IRO_TOOL_BUILD_DIR}/test_integration_emit")
file(REMOVE_RECURSE "${WORK_DIR}")
file(MAKE_DIRECTORY "${WORK_DIR}")

file(WRITE "${WORK_DIR}/probe_types.h"
"struct sample_struct {\n"
"  int x;\n"
"};\n")

set(MANIFEST_PATH "${WORK_DIR}/samplex.toml")
file(WRITE "${MANIFEST_PATH}"
"schema_version = \"1.5\"\n"
"set = \"samplex\"\n"
"includes = [\"probe_types.h\"]\n"
"\n"
"[types.sample]\n"
"c_type = \"struct sample_struct\"\n"
"fields = [\"x\"]\n")

file(WRITE "${WORK_DIR}/layout_samplex.probe.cmd"
"cc=cc\n"
"target=native\n"
"arch=x86_64\n"
"argv=636300\n")

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
          "${GEN_PROBE_BIN}"
          --manifest "${MANIFEST_PATH}"
          --out "${WORK_DIR}/layout_samplex.probe.c"
  RESULT_VARIABLE GEN_PROBE_RC
  OUTPUT_VARIABLE GEN_PROBE_OUT
  ERROR_VARIABLE GEN_PROBE_ERR
)
if(NOT GEN_PROBE_RC EQUAL 0)
  message(FATAL_ERROR "gen_probe failed:\n${GEN_PROBE_OUT}\n${GEN_PROBE_ERR}")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
          "${LAYOUT_PARSE_BIN}"
          --manifest "${MANIFEST_PATH}"
          --probe-cmd "${WORK_DIR}/layout_samplex.probe.cmd"
          --hash64
  RESULT_VARIABLE HASH_RC
  OUTPUT_VARIABLE HASH_OUT
  ERROR_VARIABLE HASH_ERR
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT HASH_RC EQUAL 0)
  message(FATAL_ERROR "layout_parse --hash64 failed:\n${HASH_OUT}\n${HASH_ERR}")
endif()

file(WRITE "${WORK_DIR}/layout_samplex.probe.hash.h"
"/* Auto-generated by integration test. */\n"
"#define IRO_PROBE_INPUT_HASH64 ${HASH_OUT}ull\n")

execute_process(
  COMMAND "${CC_EXECUTABLE}" -std=gnu11 "-I${WORK_DIR}"
          -c "${WORK_DIR}/layout_samplex.probe.c"
          -o "${WORK_DIR}/layout_samplex.probe.o"
  RESULT_VARIABLE CC_RC
  OUTPUT_VARIABLE CC_OUT
  ERROR_VARIABLE CC_ERR
)
if(NOT CC_RC EQUAL 0)
  message(FATAL_ERROR "probe compile failed:\n${CC_OUT}\n${CC_ERR}")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
          "${LAYOUT_PARSE_BIN}"
          --manifest "${MANIFEST_PATH}"
          --probe "${WORK_DIR}/layout_samplex.probe.o"
          --probe-cmd "${WORK_DIR}/layout_samplex.probe.cmd"
          --outdir "${WORK_DIR}"
          --emit
  RESULT_VARIABLE EMIT1_RC
  OUTPUT_VARIABLE EMIT1_OUT
  ERROR_VARIABLE EMIT1_ERR
)
if(NOT EMIT1_RC EQUAL 0)
  message(FATAL_ERROR "layout_parse --emit (1) failed:\n${EMIT1_OUT}\n${EMIT1_ERR}")
endif()

set(OUT_H "${WORK_DIR}/include/generated/iro/layout_samplex.h")
set(OUT_HPP "${WORK_DIR}/include/generated/iro/layout_samplex.hpp")
set(OUT_META "${WORK_DIR}/include/generated/iro/layout_samplex.meta")
set(OUT_STAMP "${WORK_DIR}/include/generated/iro/layout_samplex.stamp")
foreach(f IN LISTS OUT_H OUT_HPP OUT_META OUT_STAMP)
  if(NOT EXISTS "${f}")
    message(FATAL_ERROR "Missing expected output: ${f}")
  endif()
endforeach()

file(COPY_FILE "${OUT_H}" "${WORK_DIR}/first.h")
file(COPY_FILE "${OUT_HPP}" "${WORK_DIR}/first.hpp")
file(COPY_FILE "${OUT_META}" "${WORK_DIR}/first.meta")
file(COPY_FILE "${OUT_STAMP}" "${WORK_DIR}/first.stamp")

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
          "${LAYOUT_PARSE_BIN}"
          --manifest "${MANIFEST_PATH}"
          --probe "${WORK_DIR}/layout_samplex.probe.o"
          --probe-cmd "${WORK_DIR}/layout_samplex.probe.cmd"
          --outdir "${WORK_DIR}"
          --emit
  RESULT_VARIABLE EMIT2_RC
  OUTPUT_VARIABLE EMIT2_OUT
  ERROR_VARIABLE EMIT2_ERR
)
if(NOT EMIT2_RC EQUAL 0)
  message(FATAL_ERROR "layout_parse --emit (2) failed:\n${EMIT2_OUT}\n${EMIT2_ERR}")
endif()

function(assert_same_text first_file second_file)
  file(READ "${first_file}" FIRST_TEXT)
  file(READ "${second_file}" SECOND_TEXT)
  if(NOT FIRST_TEXT STREQUAL SECOND_TEXT)
    message(FATAL_ERROR "Determinism check failed for ${second_file}")
  endif()
endfunction()

assert_same_text("${WORK_DIR}/first.h" "${OUT_H}")
assert_same_text("${WORK_DIR}/first.hpp" "${OUT_HPP}")
assert_same_text("${WORK_DIR}/first.meta" "${OUT_META}")
assert_same_text("${WORK_DIR}/first.stamp" "${OUT_STAMP}")

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
          "${LAYOUT_PARSE_BIN}"
          --manifest "${MANIFEST_PATH}"
          --probe "${WORK_DIR}/layout_samplex.probe.o"
          --probe-cmd "${WORK_DIR}/layout_samplex.probe.cmd"
          --outdir "${WORK_DIR}"
          --verify
  RESULT_VARIABLE VERIFY_RC
  OUTPUT_VARIABLE VERIFY_OUT
  ERROR_VARIABLE VERIFY_ERR
)
if(NOT VERIFY_RC EQUAL 0)
  message(FATAL_ERROR "layout_parse --verify failed:\n${VERIFY_OUT}\n${VERIFY_ERR}")
endif()
