cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED IRO_TOOL_ROOT)
  message(FATAL_ERROR "IRO_TOOL_ROOT is required")
endif()
if(NOT DEFINED IRO_TOOL_BUILD_DIR)
  message(FATAL_ERROR "IRO_TOOL_BUILD_DIR is required")
endif()

set(GEN_PROBE_BIN "${IRO_TOOL_BUILD_DIR}/gen_probe")
set(LAYOUT_PARSE_BIN "${IRO_TOOL_BUILD_DIR}/layout_parse")
if(NOT EXISTS "${GEN_PROBE_BIN}")
  message(FATAL_ERROR "Missing required binary: ${GEN_PROBE_BIN}")
endif()
if(NOT EXISTS "${LAYOUT_PARSE_BIN}")
  message(FATAL_ERROR "Missing required binary: ${LAYOUT_PARSE_BIN}")
endif()

if(DEFINED IRO_TOOL_C_COMPILER AND NOT IRO_TOOL_C_COMPILER STREQUAL "")
  set(C_COMPILER "${IRO_TOOL_C_COMPILER}")
else()
  find_program(C_COMPILER NAMES cc clang gcc)
endif()
if(NOT C_COMPILER)
  message(FATAL_ERROR "No C compiler found")
endif()

execute_process(
  COMMAND uname -m
  RESULT_VARIABLE UNAME_RC
  OUTPUT_VARIABLE HOST_ARCH_RAW
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT UNAME_RC EQUAL 0)
  message(FATAL_ERROR "Failed to detect host arch with uname -m")
endif()
if(HOST_ARCH_RAW STREQUAL "arm64")
  set(HOST_ARCH "aarch64")
else()
  set(HOST_ARCH "${HOST_ARCH_RAW}")
endif()

set(WORK_ROOT "${IRO_TOOL_BUILD_DIR}/test_dwarf_fixtures")
file(REMOVE_RECURSE "${WORK_ROOT}")
file(MAKE_DIRECTORY "${WORK_ROOT}")

function(run_checked label)
  execute_process(
    COMMAND ${ARGN}
    RESULT_VARIABLE RC
    OUTPUT_VARIABLE OUT
    ERROR_VARIABLE ERR
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_STRIP_TRAILING_WHITESPACE
  )
  if(NOT RC EQUAL 0)
    message(FATAL_ERROR "${label} failed:\n${OUT}\n${ERR}")
  endif()
endfunction()

function(assert_same_text first_file second_file)
  file(READ "${first_file}" FIRST_TEXT)
  file(READ "${second_file}" SECOND_TEXT)
  if(NOT FIRST_TEXT STREQUAL SECOND_TEXT)
    message(FATAL_ERROR "Determinism check failed for ${second_file}")
  endif()
endfunction()

function(prepare_probe_cmd out_path)
  file(WRITE "${out_path}"
    "cc=${C_COMPILER}\n"
    "target=native\n"
    "arch=${HOST_ARCH}\n"
    "argv=636300\n")
endfunction()

function(run_common_pipeline fixture_name extra_sources)
  set(FIXTURE_SRC "${IRO_TOOL_ROOT}/tests/fixtures/${fixture_name}")
  set(FIXTURE_WORK "${WORK_ROOT}/${fixture_name}")
  file(COPY "${FIXTURE_SRC}/" DESTINATION "${FIXTURE_WORK}")

  set(MANIFEST "${FIXTURE_WORK}/${fixture_name}.toml")
  set(PROBE_C "${FIXTURE_WORK}/layout_${fixture_name}.probe.c")
  set(PROBE_O "${FIXTURE_WORK}/layout_${fixture_name}.probe.o")
  set(PROBE_CMD "${FIXTURE_WORK}/layout_${fixture_name}.probe.cmd")
  set(PROBE_HASH_H "${FIXTURE_WORK}/layout_${fixture_name}.probe.hash.h")
  set(LINKED_O "${FIXTURE_WORK}/layout_${fixture_name}.linked.o")

  prepare_probe_cmd("${PROBE_CMD}")

  run_checked("gen_probe ${fixture_name}"
    "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
    "${GEN_PROBE_BIN}"
    --manifest "${MANIFEST}"
    --out "${PROBE_C}"
  )

  execute_process(
    COMMAND "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
            "${LAYOUT_PARSE_BIN}"
            --manifest "${MANIFEST}"
            --probe-cmd "${PROBE_CMD}"
            --hash64
    RESULT_VARIABLE HASH_RC
    OUTPUT_VARIABLE HASH_OUT
    ERROR_VARIABLE HASH_ERR
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )
  if(NOT HASH_RC EQUAL 0)
    message(FATAL_ERROR "layout_parse --hash64 ${fixture_name} failed:\n${HASH_OUT}\n${HASH_ERR}")
  endif()

  file(WRITE "${PROBE_HASH_H}"
    "/* Auto-generated by integration test. */\n"
    "#define IRO_PROBE_INPUT_HASH64 ${HASH_OUT}ull\n")

  run_checked("compile probe ${fixture_name}"
    "${C_COMPILER}" -std=gnu11 -g -gdwarf-4 -gz=none "-I${FIXTURE_WORK}"
    -c "${PROBE_C}" -o "${PROBE_O}"
  )

  set(LINK_INPUTS "${PROBE_O}")
  foreach(src IN LISTS extra_sources)
    set(EXTRA_O "${FIXTURE_WORK}/${src}.o")
    run_checked("compile ${src} ${fixture_name}"
      "${C_COMPILER}" -std=gnu11 -g -gdwarf-4 -gz=none "-I${FIXTURE_WORK}"
      -c "${FIXTURE_WORK}/${src}.c" -o "${EXTRA_O}"
    )
    list(APPEND LINK_INPUTS "${EXTRA_O}")
  endforeach()

  run_checked("link -r ${fixture_name}"
    "${C_COMPILER}" -r ${LINK_INPUTS} -o "${LINKED_O}"
  )

  run_checked("layout_parse emit ${fixture_name}"
    "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
    "${LAYOUT_PARSE_BIN}"
    --manifest "${MANIFEST}"
    --probe "${LINKED_O}"
    --probe-cmd "${PROBE_CMD}"
    --outdir "${FIXTURE_WORK}"
    --emit
  )

  set(OUT_H "${FIXTURE_WORK}/include/generated/iro/layout_${fixture_name}.h")
  set(OUT_HPP "${FIXTURE_WORK}/include/generated/iro/layout_${fixture_name}.hpp")
  set(OUT_META "${FIXTURE_WORK}/include/generated/iro/layout_${fixture_name}.meta")
  set(OUT_STAMP "${FIXTURE_WORK}/include/generated/iro/layout_${fixture_name}.stamp")
  foreach(f IN LISTS OUT_H OUT_HPP OUT_META OUT_STAMP)
    if(NOT EXISTS "${f}")
      message(FATAL_ERROR "Missing generated output for ${fixture_name}: ${f}")
    endif()
  endforeach()

  file(COPY_FILE "${OUT_H}" "${FIXTURE_WORK}/first.h")
  file(COPY_FILE "${OUT_HPP}" "${FIXTURE_WORK}/first.hpp")
  file(COPY_FILE "${OUT_META}" "${FIXTURE_WORK}/first.meta")
  file(COPY_FILE "${OUT_STAMP}" "${FIXTURE_WORK}/first.stamp")

  run_checked("layout_parse emit rerun ${fixture_name}"
    "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
    "${LAYOUT_PARSE_BIN}"
    --manifest "${MANIFEST}"
    --probe "${LINKED_O}"
    --probe-cmd "${PROBE_CMD}"
    --outdir "${FIXTURE_WORK}"
    --emit
  )

  assert_same_text("${FIXTURE_WORK}/first.h" "${OUT_H}")
  assert_same_text("${FIXTURE_WORK}/first.hpp" "${OUT_HPP}")
  assert_same_text("${FIXTURE_WORK}/first.meta" "${OUT_META}")
  assert_same_text("${FIXTURE_WORK}/first.stamp" "${OUT_STAMP}")

  run_checked("layout_parse verify ${fixture_name}"
    "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
    "${LAYOUT_PARSE_BIN}"
    --manifest "${MANIFEST}"
    --probe "${LINKED_O}"
    --probe-cmd "${PROBE_CMD}"
    --outdir "${FIXTURE_WORK}"
    --verify
  )

  set(${fixture_name}_OUT_H "${OUT_H}" PARENT_SCOPE)
  set(${fixture_name}_LINKED_O "${LINKED_O}" PARENT_SCOPE)
endfunction()

run_common_pipeline("negative_enum" "probe_enum_anchor")
file(READ "${negative_enum_OUT_H}" NEG_HEADER)
if(NOT NEG_HEADER MATCHES "#define IRO_ENUM__enum_sample_enum__SAMPLE_NEG_ONE \\(-1ll\\)")
  message(FATAL_ERROR "negative_enum fixture: missing signed -1 emission")
endif()
if(NOT NEG_HEADER MATCHES "#define IRO_ENUM__enum_sample_enum__SAMPLE_NEG_BIG \\(-128ll\\)")
  message(FATAL_ERROR "negative_enum fixture: missing signed -128 emission")
endif()
if(NOT NEG_HEADER MATCHES "#define IRO_ENUM__enum_sample_enum__SAMPLE_POS 7ull")
  message(FATAL_ERROR "negative_enum fixture: missing unsigned positive emission")
endif()

# Malformed DWARF overflow regression: corrupt first .debug_info unit length.
set(OVERFLOW_OBJ "${WORK_ROOT}/negative_enum_overflow.linked.o")
file(COPY_FILE "${negative_enum_LINKED_O}" "${OVERFLOW_OBJ}")

execute_process(
  COMMAND readelf -W -S "${OVERFLOW_OBJ}"
  RESULT_VARIABLE READelf_RC
  OUTPUT_VARIABLE SECTIONS_OUT
  ERROR_VARIABLE SECTIONS_ERR
)
if(NOT READelf_RC EQUAL 0)
  message(FATAL_ERROR "readelf failed while preparing overflow fixture:\n${SECTIONS_OUT}\n${SECTIONS_ERR}")
endif()

string(REGEX MATCH "\\.debug_info[ ]+PROGBITS[ ]+[0-9a-fA-F]+[ ]+([0-9a-fA-F]+)[ ]+([0-9a-fA-F]+)"
       _ "${SECTIONS_OUT}")
if(NOT CMAKE_MATCH_1)
  message(FATAL_ERROR "Failed to parse .debug_info offset from readelf output")
endif()
set(DEBUG_INFO_OFF_HEX "${CMAKE_MATCH_1}")
math(EXPR DEBUG_INFO_OFF_DEC "0x${DEBUG_INFO_OFF_HEX}")

execute_process(
  COMMAND bash -lc "printf '\\376\\377\\377\\377' | dd of='${OVERFLOW_OBJ}' bs=1 seek=${DEBUG_INFO_OFF_DEC} conv=notrunc status=none"
  RESULT_VARIABLE PATCH_RC
  OUTPUT_VARIABLE PATCH_OUT
  ERROR_VARIABLE PATCH_ERR
)
if(NOT PATCH_RC EQUAL 0)
  message(FATAL_ERROR "Failed to patch malformed overflow fixture:\n${PATCH_OUT}\n${PATCH_ERR}")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
          "${LAYOUT_PARSE_BIN}"
          --manifest "${WORK_ROOT}/negative_enum/negative_enum.toml"
          --probe "${OVERFLOW_OBJ}"
          --probe-cmd "${WORK_ROOT}/negative_enum/layout_negative_enum.probe.cmd"
          --outdir "${WORK_ROOT}/negative_enum"
          --emit
  RESULT_VARIABLE OVERFLOW_RC
  OUTPUT_VARIABLE OVERFLOW_OUT
  ERROR_VARIABLE OVERFLOW_ERR
)
if(OVERFLOW_RC EQUAL 0)
  message(FATAL_ERROR "Malformed DWARF overflow regression failed: corrupted .debug_info unexpectedly succeeded")
endif()
if(NOT OVERFLOW_ERR MATCHES "DWARF:")
  message(FATAL_ERROR
    "Malformed DWARF overflow regression failed: missing DWARF diagnostic.\\n"
    "stdout:\\n${OVERFLOW_OUT}\\n"
    "stderr:\\n${OVERFLOW_ERR}")
endif()

run_common_pipeline("negative_enum_explicit" "")
file(READ "${negative_enum_explicit_OUT_H}" NEG_EXPL_HEADER)
if(NOT NEG_EXPL_HEADER MATCHES "#define IRO_ENUM__enum_sample_enum__SAMPLE_NEG_ONE \\(-1ll\\)")
  message(FATAL_ERROR "negative_enum_explicit fixture: missing signed -1 emission")
endif()
if(NOT NEG_EXPL_HEADER MATCHES "#define IRO_ENUM__enum_sample_enum__SAMPLE_NEG_BIG \\(-128ll\\)")
  message(FATAL_ERROR "negative_enum_explicit fixture: missing signed -128 emission")
endif()
if(NOT NEG_EXPL_HEADER MATCHES "#define IRO_ENUM__enum_sample_enum__SAMPLE_POS 7ull")
  message(FATAL_ERROR "negative_enum_explicit fixture: missing unsigned positive emission")
endif()

set(MULTI_EXTRA "probe_extra_a;probe_extra_b")
run_common_pipeline("multi_unit" "${MULTI_EXTRA}")
file(READ "${multi_unit_OUT_H}" MULTI_HEADER)
if(NOT MULTI_HEADER MATCHES "#define IRO_OFFSETOF__struct_common_type__a 0ull")
  message(FATAL_ERROR "multi_unit fixture: missing offset for field a")
endif()
if(NOT MULTI_HEADER MATCHES "#define IRO_OFFSETOF__struct_common_type__b 4ull")
  message(FATAL_ERROR "multi_unit fixture: missing offset for field b")
endif()

# Malformed object regression: parser must fail cleanly on invalid ELF payloads.
set(MALFORMED_OBJ "${WORK_ROOT}/malformed_probe.o")
file(WRITE "${MALFORMED_OBJ}" "not-an-elf")
execute_process(
  COMMAND "${CMAKE_COMMAND}" -E env "ASAN_OPTIONS=detect_leaks=0"
          "${LAYOUT_PARSE_BIN}"
          --manifest "${WORK_ROOT}/negative_enum/negative_enum.toml"
          --probe "${MALFORMED_OBJ}"
          --probe-cmd "${WORK_ROOT}/negative_enum/layout_negative_enum.probe.cmd"
          --outdir "${WORK_ROOT}/negative_enum"
          --emit
  RESULT_VARIABLE MALFORMED_RC
  OUTPUT_VARIABLE MALFORMED_OUT
  ERROR_VARIABLE MALFORMED_ERR
)
if(MALFORMED_RC EQUAL 0)
  message(FATAL_ERROR "Malformed object regression failed: invalid ELF unexpectedly succeeded")
endif()
if(NOT MALFORMED_ERR MATCHES "(not an ELF file|object too small for ELF header)")
  message(FATAL_ERROR
    "Malformed object regression failed: expected ELF-format diagnostic.\\n"
    "stdout:\\n${MALFORMED_OUT}\\n"
    "stderr:\\n${MALFORMED_ERR}")
endif()
