# Probe generation + parsing pipeline

IRO_LAYOUTS := $(iro-layout-y)

ifeq ($(CONFIG_IRO),y)
  ifeq ($(strip $(IRO_LAYOUTS)),)
    ifeq ($(CONFIG_IRO_STRICT),y)
      $(error IRO: CONFIG_IRO enabled but iro-layout-y is empty)
    else
      $(warning IRO: CONFIG_IRO enabled but iro-layout-y is empty -- no layouts will be processed)
    endif
  endif
endif

IRO_GEN_DIR := $(objtree)/iro/generated
IRO_OUT_DIR := $(objtree)/include/generated/iro

IRO_MANIFEST      := $(patsubst %, $(srctree)/iro/layout/%.toml, $(IRO_LAYOUTS))
IRO_PROBE_C       := $(patsubst %, $(IRO_GEN_DIR)/layout_%.probe.c, $(IRO_LAYOUTS))
IRO_PROBE_O       := $(patsubst %, $(IRO_GEN_DIR)/layout_%.probe.o, $(IRO_LAYOUTS))
IRO_PROBE_CMD     := $(patsubst %, $(IRO_GEN_DIR)/layout_%.probe.cmd, $(IRO_LAYOUTS))
IRO_PROBE_HASH_H  := $(patsubst %, $(IRO_GEN_DIR)/layout_%.probe.hash.h, $(IRO_LAYOUTS))
IRO_STAMPS        := $(patsubst %, $(IRO_OUT_DIR)/layout_%.stamp, $(IRO_LAYOUTS))

# Some Kbuild helpers rely on $(targets) membership for cmd/deps tracking/clean.
targets += $(IRO_PROBE_C) $(IRO_PROBE_O) $(IRO_PROBE_CMD) $(IRO_PROBE_HASH_H) $(IRO_STAMPS)

$(IRO_GEN_DIR):
	$(Q)mkdir -p $@

# The probe transport artifact MUST be a normal ELF object even under LTO builds.
$(foreach s,$(IRO_LAYOUTS),$(eval CFLAGS_layout_$(s).probe.o += -fno-lto))
# DWARF is required for bitfield geometry and extract_all enums.
$(foreach s,$(IRO_LAYOUTS),$(eval CFLAGS_layout_$(s).probe.o += -g))

$(IRO_GEN_DIR)/layout_%.probe.c: $(srctree)/iro/layout/%.toml $(IRO_GEN_PROBE) | $(IRO_GEN_DIR)
	$(Q)$(IRO_GEN_PROBE) --manifest $< --out $@

# Side-effect targets:
# - layout_%.probe.cmd (canonical compile description; spec §6.2)
# - layout_%.probe.hash.h (provides IRO_PROBE_INPUT_HASH64 without self-referential argv)
# Steps:
#  1) Capture the real compile command from $(cmd_cc_o_c).
#  2) Normalize srctree/objtree paths for deterministic probe.cmd.
#  3) Emit probe.cmd with cmp/mv idempotence.
#  4) Regenerate probe.hash.h only when inputs changed, also with cmp/mv idempotence.
$(IRO_GEN_DIR)/layout_%.probe.o: $(IRO_GEN_DIR)/layout_%.probe.c $(srctree)/iro/layout/%.toml $(IRO_LAYOUT_PARSE) FORCE | $(IRO_GEN_DIR)
	$(Q)set -eu; \
	  cmd='$(cmd_cc_o_c)'; \
	  srctree='$(srctree)'; objtree='$(objtree)'; \
	  srctree_ph='$''{SRCTREE}'; objtree_ph='$''{OBJTREE}'; \
	  if [ "$${srctree#/}" != "$$srctree" ]; then \
	    cmd=$$(printf '%s' "$$cmd" | sed "s|$$srctree|$$srctree_ph|g"); \
	  fi; \
	  if [ "$${objtree#/}" != "$$objtree" ]; then \
	    cmd=$$(printf '%s' "$$cmd" | sed "s|$$objtree|$$objtree_ph|g"); \
	  fi; \
	  set -- $$cmd; \
	  cc="$$1"; \
	  if [ "$$cc" = "ccache" ] || [ "$$cc" = "sccache" ]; then \
	    [ -n "$${2:-}" ] && cc="$$2"; \
	  fi; \
	  arch='$(UTS_MACHINE)'; \
	  if [ -z "$$arch" ]; then arch='$(ARCH)'; fi; \
	  case "$$arch" in arm64) arch=aarch64 ;; x86) arch=x86_64 ;; esac; \
	  target=""; \
	  for a in "$$@"; do case "$$a" in --target=*) target=$${a#--target=} ;; esac; done; \
	  if [ -z "$$target" ]; then \
	    if [ -n "$(CROSS_COMPILE)" ]; then target='$(patsubst %-,%,$(CROSS_COMPILE))'; else target=native; fi; \
	  fi; \
	  argv_hex=$$(printf '%s\\000' "$$@" | od -An -tx1 -v | tr -d ' \\n' | tr 'A-F' 'a-f'); \
	  out_cmd='$(IRO_GEN_DIR)/layout_$*.probe.cmd'; tmp_cmd="$${out_cmd}.tmp"; \
	  { \
	    printf 'cc=%s\\n' "$$cc"; \
	    printf 'target=%s\\n' "$$target"; \
	    printf 'arch=%s\\n' "$$arch"; \
	    printf 'argv=%s\\n' "$$argv_hex"; \
	  } >"$$tmp_cmd"; \
	  if [ -f "$$out_cmd" ] && cmp -s "$$out_cmd" "$$tmp_cmd"; then rm -f "$$tmp_cmd"; else mv -f "$$tmp_cmd" "$$out_cmd"; fi; \
	  out_h='$(IRO_GEN_DIR)/layout_$*.probe.hash.h'; tmp_h="$${out_h}.tmp"; \
	  if [ ! -f "$$out_h" ] || [ "$$out_cmd" -nt "$$out_h" ] || [ "$(IRO_LAYOUT_PARSE)" -nt "$$out_h" ] || [ "$(srctree)/iro/layout/$*.toml" -nt "$$out_h" ]; then \
	    hash=$$($(IRO_LAYOUT_PARSE) --manifest $(srctree)/iro/layout/$*.toml --probe-cmd "$$out_cmd" --hash64); \
	    { \
	      printf '/* Auto-generated by IRO (do not edit). */\\n'; \
	      printf '#define IRO_PROBE_INPUT_HASH64 %sull\\n' "$$hash"; \
	    } >"$$tmp_h"; \
	    if [ -f "$$out_h" ] && cmp -s "$$out_h" "$$tmp_h"; then rm -f "$$tmp_h"; else mv -f "$$tmp_h" "$$out_h"; fi; \
	  fi
	$(call if_changed_dep,cc_o_c)

$(IRO_GEN_DIR)/layout_%.probe.cmd $(IRO_GEN_DIR)/layout_%.probe.hash.h: $(IRO_GEN_DIR)/layout_%.probe.o
	@:

$(IRO_OUT_DIR)/layout_%.stamp: $(IRO_GEN_DIR)/layout_%.probe.o $(IRO_LAYOUT_PARSE) $(IRO_GEN_DIR)/layout_%.probe.c $(srctree)/iro/layout/%.toml
	$(Q)$(IRO_LAYOUT_PARSE) --manifest $(srctree)/iro/layout/$*.toml --probe $(IRO_GEN_DIR)/layout_$*.probe.o --probe-cmd $(IRO_GEN_DIR)/layout_$*.probe.cmd --outdir $(objtree) --emit

always-y += $(IRO_STAMPS)

.PHONY: iro-verify
iro-verify: $(IRO_STAMPS)
	$(Q)for s in $(IRO_LAYOUTS); do \
	  $(IRO_LAYOUT_PARSE) --manifest "$(srctree)/iro/layout/$${s}.toml" --probe "$(IRO_GEN_DIR)/layout_$${s}.probe.o" --probe-cmd "$(IRO_GEN_DIR)/layout_$${s}.probe.cmd" --outdir "$(objtree)" --verify || exit $$?; \
	done
