name: ci

on:
  push:
  pull_request:

jobs:
  iro-tool-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S iro-tool -B iro-tool/build

      - name: Build
        run: cmake --build iro-tool/build -j

      - name: Test
        run: ctest --test-dir iro-tool/build --output-on-failure
